<?php
/**
 * MemberCreateRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * MemberCreateRequest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MemberCreateRequest implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'members' => '\Swagger\Client\Model\Member',
        'members_users' => '\Swagger\Client\Model\MemberUser',
        'members_locations' => '\Swagger\Client\Model\MemberLocation'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'members' => 'members',
        'members_users' => 'members_users',
        'members_locations' => 'members_locations'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'members' => 'setMembers',
        'members_users' => 'setMembersUsers',
        'members_locations' => 'setMembersLocations'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'members' => 'getMembers',
        'members_users' => 'getMembersUsers',
        'members_locations' => 'getMembersLocations'
    );
  
    
    /**
      * $members 
      * @var \Swagger\Client\Model\Member
      */
    protected $members;
    
    /**
      * $members_users 
      * @var \Swagger\Client\Model\MemberUser
      */
    protected $members_users;
    
    /**
      * $members_locations 
      * @var \Swagger\Client\Model\MemberLocation
      */
    protected $members_locations;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->members = $data["members"];
            $this->members_users = $data["members_users"];
            $this->members_locations = $data["members_locations"];
        }
    }
    
    /**
     * Gets members
     * @return \Swagger\Client\Model\Member
     */
    public function getMembers()
    {
        return $this->members;
    }
  
    /**
     * Sets members
     * @param \Swagger\Client\Model\Member $members 
     * @return $this
     */
    public function setMembers($members)
    {
        
        $this->members = $members;
        return $this;
    }
    
    /**
     * Gets members_users
     * @return \Swagger\Client\Model\MemberUser
     */
    public function getMembersUsers()
    {
        return $this->members_users;
    }
  
    /**
     * Sets members_users
     * @param \Swagger\Client\Model\MemberUser $members_users 
     * @return $this
     */
    public function setMembersUsers($members_users)
    {
        
        $this->members_users = $members_users;
        return $this;
    }
    
    /**
     * Gets members_locations
     * @return \Swagger\Client\Model\MemberLocation
     */
    public function getMembersLocations()
    {
        return $this->members_locations;
    }
  
    /**
     * Sets members_locations
     * @param \Swagger\Client\Model\MemberLocation $members_locations 
     * @return $this
     */
    public function setMembersLocations($members_locations)
    {
        
        $this->members_locations = $members_locations;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
