<?php
/**
 * MerchantsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MerchantsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MerchantsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for createMember
     *
     * Creates a new Merchant
     *
     */
    public function test_createMember() {

    }
    
    /**
     * Test case for getMember
     *
     * Returns a Merchant
     *
     */
    public function test_getMember() {

    }
    
    /**
     * Test case for getMemberLocationUsers
     *
     * Returns a collection of MerchantUsers
     *
     */
    public function test_getMemberLocationUsers() {

    }
    
    /**
     * Test case for getMemberLocations
     *
     * Returns a collection of MerchantLocations
     *
     */
    public function test_getMemberLocations() {

    }
    
    /**
     * Test case for getMemberMetaIndustries
     *
     * Returns collection of industries
     *
     */
    public function test_getMemberMetaIndustries() {

    }
    
    /**
     * Test case for getMemberMetaStatuses
     *
     * Returns collection of statuses
     *
     */
    public function test_getMemberMetaStatuses() {

    }
    
    /**
     * Test case for getMemberUsers
     *
     * Returnsa a collection of MerchantUsers
     *
     */
    public function test_getMemberUsers() {

    }
    
}
